import pytest

from mini_ids.engine import DetectionEngine
from mini_ids.models import Alert, PacketInfo, Severity
from mini_ids.rules import DetectionRule


class DummyRule(DetectionRule):
    rule_id = "TEST-ENGINE"
    name = "Engine Test Rule"
    description = "A test-only rule for detection engine behavior."
    severity: Severity = "LOW"

    def __init__(self, alerts: list[Alert] | None = None) -> None:
        self.alerts = alerts if alerts is not None else []
        self.processed_packets: list[PacketInfo] = []

    def process_packet(self, packet: PacketInfo) -> list[Alert]:
        self.processed_packets.append(packet)
        return list(self.alerts)


class RaisingRule(DummyRule):
    def process_packet(self, packet: PacketInfo) -> list[Alert]:
        raise RuntimeError("rule failed")


def make_alert(rule_id: str, severity: Severity) -> Alert:
    return Alert(
        timestamp="2024-07-03T09:46:40Z",
        rule_id=rule_id,
        rule_name=f"Rule {rule_id}",
        severity=severity,
        description="Test alert generated by a dummy rule.",
    )


def test_engine_can_be_created_without_rules() -> None:
    engine = DetectionEngine()

    assert engine.rules == ()
    assert engine.get_summary() == {
        "packets_processed": 0,
        "alerts_generated": 0,
        "severity_counts": {
            "LOW": 0,
            "MEDIUM": 0,
            "HIGH": 0,
            "CRITICAL": 0,
        },
    }


def test_engine_accepts_initial_rules_and_registers_more_rules() -> None:
    first_rule = DummyRule()
    second_rule = DummyRule()
    engine = DetectionEngine([first_rule])

    engine.register_rule(second_rule)

    assert engine.rules == (first_rule, second_rule)


def test_one_packet_is_passed_to_every_registered_rule(
    normal_tcp_packets: list[PacketInfo],
) -> None:
    first_rule = DummyRule()
    second_rule = DummyRule()
    engine = DetectionEngine([first_rule, second_rule])
    packet = normal_tcp_packets[0]

    engine.process_packet(packet)

    assert first_rule.processed_packets == [packet]
    assert second_rule.processed_packets == [packet]


def test_processing_packet_can_return_no_alerts(
    normal_tcp_packets: list[PacketInfo],
) -> None:
    engine = DetectionEngine([DummyRule()])

    assert engine.process_packet(normal_tcp_packets[0]) == []


def test_processing_packet_collects_alerts_from_multiple_rules(
    normal_tcp_packets: list[PacketInfo],
) -> None:
    low_alert = make_alert("RULE-A", "LOW")
    high_alert = make_alert("RULE-B", "HIGH")
    engine = DetectionEngine(
        [DummyRule([low_alert]), DummyRule([high_alert])]
    )

    alerts = engine.process_packet(normal_tcp_packets[0])

    assert alerts == [low_alert, high_alert]


def test_alert_order_follows_rule_registration_and_rule_result_order(
    normal_tcp_packets: list[PacketInfo],
) -> None:
    first = make_alert("RULE-A-1", "LOW")
    second = make_alert("RULE-A-2", "MEDIUM")
    third = make_alert("RULE-B-1", "HIGH")
    engine = DetectionEngine(
        [DummyRule([first, second]), DummyRule([third])]
    )

    alerts = engine.process_packet(normal_tcp_packets[0])

    assert alerts == [first, second, third]


def test_packet_count_increments_once_per_packet_not_per_rule(
    normal_tcp_packets: list[PacketInfo],
) -> None:
    engine = DetectionEngine([DummyRule(), DummyRule(), DummyRule()])

    engine.process_packet(normal_tcp_packets[0])

    assert engine.get_summary()["packets_processed"] == 1


def test_total_alert_count_is_tracked(
    normal_tcp_packets: list[PacketInfo],
) -> None:
    engine = DetectionEngine(
        [
            DummyRule([make_alert("RULE-A", "LOW")]),
            DummyRule(
                [
                    make_alert("RULE-B", "MEDIUM"),
                    make_alert("RULE-C", "HIGH"),
                ]
            ),
        ]
    )

    engine.process_packet(normal_tcp_packets[0])

    assert engine.get_summary()["alerts_generated"] == 3


def test_alert_counts_are_tracked_by_severity(
    normal_tcp_packets: list[PacketInfo],
) -> None:
    alerts = [
        make_alert("LOW-1", "LOW"),
        make_alert("MEDIUM-1", "MEDIUM"),
        make_alert("MEDIUM-2", "MEDIUM"),
        make_alert("HIGH-1", "HIGH"),
        make_alert("CRITICAL-1", "CRITICAL"),
    ]
    engine = DetectionEngine([DummyRule(alerts)])

    engine.process_packet(normal_tcp_packets[0])

    assert engine.get_summary()["severity_counts"] == {
        "LOW": 1,
        "MEDIUM": 2,
        "HIGH": 1,
        "CRITICAL": 1,
    }


def test_engine_processes_an_iterable_of_packets(
    mixed_normal_packets: list[PacketInfo],
) -> None:
    alert = make_alert("RULE-A", "LOW")
    engine = DetectionEngine([DummyRule([alert])])

    alerts = engine.process_packets(packet for packet in mixed_normal_packets)

    assert alerts == [alert] * len(mixed_normal_packets)
    assert engine.get_summary()["packets_processed"] == len(mixed_normal_packets)
    assert engine.get_summary()["alerts_generated"] == len(mixed_normal_packets)


def test_stateful_rule_preserves_state_across_packets(
    normal_tcp_packets: list[PacketInfo],
) -> None:
    rule = DummyRule()
    engine = DetectionEngine([rule])

    engine.process_packets(normal_tcp_packets)

    assert rule.processed_packets == normal_tcp_packets


def test_rule_exception_propagates_without_updating_packet_statistics(
    normal_tcp_packets: list[PacketInfo],
) -> None:
    successful_rule = DummyRule([make_alert("RULE-A", "LOW")])
    engine = DetectionEngine([successful_rule, RaisingRule()])
    packet = normal_tcp_packets[0]

    with pytest.raises(RuntimeError, match="rule failed"):
        engine.process_packet(packet)

    assert successful_rule.processed_packets == [packet]
    assert engine.get_summary() == {
        "packets_processed": 0,
        "alerts_generated": 0,
        "severity_counts": {
            "LOW": 0,
            "MEDIUM": 0,
            "HIGH": 0,
            "CRITICAL": 0,
        },
    }


def test_engine_operates_on_packet_info_without_scapy(
    normal_tcp_packets: list[PacketInfo],
) -> None:
    rule = DummyRule()
    engine = DetectionEngine([rule])
    packet = normal_tcp_packets[0]

    engine.process_packet(packet)

    assert isinstance(rule.processed_packets[0], PacketInfo)


def test_reset_statistics_does_not_reset_rules_or_rule_state(
    normal_tcp_packets: list[PacketInfo],
) -> None:
    alert = make_alert("RULE-A", "LOW")
    rule = DummyRule([alert])
    engine = DetectionEngine([rule])
    engine.process_packet(normal_tcp_packets[0])

    engine.reset_statistics()

    assert engine.rules == (rule,)
    assert rule.processed_packets == [normal_tcp_packets[0]]
    assert engine.get_summary() == {
        "packets_processed": 0,
        "alerts_generated": 0,
        "severity_counts": {
            "LOW": 0,
            "MEDIUM": 0,
            "HIGH": 0,
            "CRITICAL": 0,
        },
    }
